#! /bin/bash

playback_info() {
   if [ -z $(which playerctl) ]
   then
      echo "(playerctl not installed)"
   else
      title=$(playerctl metadata | grep -o :title.* | awk '{s=""; for (i=2; i<=NF; i++) s=s$i" "; print s}')
      if [ ! -z "$title" ]
      then
         title_ellipsis=$(echo $title | cut -c 1-40)
         if [ $(echo $title_ellipsis | wc -c) -lt $(echo $title | wc -c) ]
         then
            title_ellipsis="$title_ellipsis..."
         fi
         echo "$(playerctl status) $title_ellipsis"
      else
         echo "(No media player)"
      fi
   fi
}

storage_info() {
   echo "$((100-$(df / | grep -oE [0-9]+% | head -n 1 | grep -o [0-9]*)))%"
}

network_info() {
   if [ -z $(which nmcli) ]
   then
      echo "n/a (nmcli not installed)"
   else
      nmcli | grep \\bconnected || echo disconnected | head -n 1
   fi
}

brightness() {
if [ -z $(which brightnessctl) ]
then
   echo "n/a (brightnessctl not installed)"
else
   device=$(brightnessctl | head -n 1 | awk '{print $2}' | grep -o "[^\']*")
   brightnessctl -d $device | grep Current | grep -oP \\d+% | head -n 1
fi
}

volume() {
   if [ -z $(which amixer) ]
   then
      echo "n/a (amixer not installed)"
   else
      current_volume=$(amixer -M get Master | tail -n 1 | grep -o [0-9]*%)
      if [ -z $(amixer -M get Master | tail -n 1 | grep off) ]
      then
         echo $current_volume
      else
         echo "$current_volume (muted)"
      fi
   fi
}

battery_info() {
   power_supply_dir=/sys/class/power_supply
   if [ -z "$(ls $power_supply_dir | grep -i bat)" ]
   then
      echo n/a
   else
      battery_dir=/sys/class/power_supply/BAT0
      charge_full=$(cat $battery_dir/charge_full)
      charge_now=$(cat $battery_dir/charge_now)
      let "battery_percent=100*$charge_now/$charge_full"
      battery_status=$(cat $battery_dir/status)
      echo "$battery_percent% ($battery_status)"
   fi
}

date_time() {
   date +"%Y-%m-%d %I:%M:%S %p"
}

echo "$(playback_info) | Storage: $(storage_info) | Network: $(network_info) | Brightness: $(brightness) | Volume: $(volume) | Battery: $(battery_info) | $(date_time) "

